### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by dagwieers**
These changes include:
- Check-mode support
- Cosmetic changes to documentation
- Examples in YAML format
- Removal of incorrect requirements (for this module)
- Do not log passwords
- Implement native `fetch_url` instead of requests
- Add alias `src` for parameter `config_file`
- Add mutual exclusive `content` option for inline data (and show some inline examples)
- Add `validate_certs` option
- Handling ACI result output (identical for JSON as XML input)
- Parse/expose ACI error output to user

### CODE REVIEW

**Comment by dagwieers** [comment]
In the meantime I have implemented all of the stuff above. And also implemented DELETE support and changes to the interface. These are now the options:
```yaml
options:
  path:
    description:
      - URI being used to execute API calls.
      - Must end in C(.xml) or C(.json).
    required: true
    aliases: [ uri ]
  host:
    description:
      - IP Address or hostname of APIC resolvable by Ansible control host.
    required: true
  method:
    description:
      - The HTTP method of the request or response. It MUST be uppercase.
    required: true
    default: GET
    choices: [ DELETE, GET, POST ]
    aliases: [ action ]
  config_file:
    description:
      - Name of the absolute path of the filname that includes the body
        of the http request being sent to the ACI fabric.
  user:
    description:
      - Username used to login to the switch.
    required: true
    default: admin
    aliases: [ username ]
  password:
    description:
      - The password to use for authentication.
    required: true
    default: C1sco12345
  protocol:
    description:
      - Connection protocol to use.
    default: https
    choices: [ http, https ]
  timeout:
    description:
      - The socket level timeout in seconds.
    default: 30
  validate_certs:
    description:
      - If C(no), SSL certificates will not be validated. This should only set to C(no) used on personally controlled sites using self-signed certificates. Prior to 1.9.2 the code defaulted to C(no).
    default: 'yes'
    choices: [ 'no', 'yes' ]
```
And the examples changed to:
```yaml
# Add a tenant
- aci_rest:
    config_file: /home/cisco/ansible/aci/configs/aci_config.xml
    path: /api/mo/uni.xml
    method: POST
    host: '{{ inventory_hostname }}'
    user: '{{ user }}'
    password: '{{ pass }}'
  delegate_to: localhost

# Get tenants
- aci_rest:
    path: /api/node/class/fvTenant.json
    method: GET
    host: '{{ inventory_hostname }}'
    user: '{{ user }}'
    password: '{{ pass }}'
  delegate_to: localhost

# Configure contracts
- aci_rest:
    config_file: /home/cisco/ansible/aci/configs/contract_config.xml
    path: /api/mo/uni.xml
    method: POST
    host: {{ inventory_hostname }}
    user: '{{ user }}'
    password: '{{ pass }}'
  delegate_to: localhost
```

And I made sure the output (RETURN) now always returns:
```yaml
response:
    description: HTTP response string
    returned: always
    type: string
    sample: OK
status:
    description: HTTP status code
    returned: always
    type: int
    sample: 200
```

@jedelman8 What do we do to go forward ? I can upstream aci_rest (in your name), make you maintainer and we work upstream on aci_rest ? This would allow me (and others) to send in improvements and discuss the interface moving forward. The other modules are not yet used for our project at this time.

**Comment by dagwieers** [comment]
So the `content` option allows us to template the REST content inline:
```
  - name: Register leaves and spines
    aci_rest:
      path: /api/mo/uni/controller/nodeidentpol.xml
      method: POST
      content: |
        {
          "fabricNodeIdentPol": {
            "fabricNodeIdentP": {
              "attributes": {
                "name": "{{ item.name }}",
                "nodeId": "{{ item.id }}",
                "status": "created,modified",
                "serial": "{{ item.serial }}"
              }
            }
          }
        }
      host: '{{ ansible_host }}'
      user: '{{ apic_username }}'
      password: '{{ apic_password }}'
      validate_certs: no
    with_items:
    - '{{ apic_leavesspines }}'
```

The other option is that we add an aci_rest action plugin doing the templating of `config_file` automatically for the user.

**Comment by dagwieers** [comment]
Also my implementation of the module no longers requires requests and json itself.

**Comment by dagwieers** [comment]
@jedelman8 These changes are ready to be merged. Any feedback ?

**Comment by jedelman8** [comment]
Merging :)  can you verify which version you tested with?

**Comment by dagwieers** [comment]
jedelman8: We tested with a variety of versions (don't have an exact list ATM), but it should not be hard to test against any TAC supported version with out scenario's. I will ask for this.

BTW The specific XML or JSON used may not be supported, do you have a specific payload you want me to test that is guaranteed to work ? If not, I will ask one of the experts...

**Comment by dagwieers** [comment]
Succesfully tested against 26 different systems with the below versions installed:
- 2.0(2l)
- 2.0(2m)
- 2.2(1n)
- 2.2(1o)
Are there any versions in particular you want me to test this on ?

**Pull request merged**
